# Generated by Django 5.2.4 on 2025-07-27 00:21

import django.db.models.deletion
from django.db import migrations, models

def set_default_cotizacion(apps, schema_editor):
    """Asigna una cotización existente a los productos que tengan NULL"""
    ProductoCotizacion = apps.get_model('cotizaciones', 'ProductoCotizacion')
    Cotizacion = apps.get_model('cotizaciones', 'Cotizacion')
    
    # Buscamos cualquier cotización existente
    if Cotizacion.objects.exists():
        default_cotizacion = Cotizacion.objects.first()
        ProductoCotizacion.objects.filter(cotizacion__isnull=True).update(cotizacion=default_cotizacion)
    else:
        # Si no hay cotizaciones, creamos una dummy para evitar errores
        default_cotizacion = Cotizacion.objects.create(
            numero="TEMP-000001-1",
            cliente="Cliente Temporal",
            total=0
        )
        ProductoCotizacion.objects.filter(cotizacion__isnull=True).update(cotizacion=default_cotizacion)

class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        # Primero actualizamos los registros NULL
        migrations.RunPython(set_default_cotizacion),
        
        # Luego aplicamos los cambios de campos
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productocotizacion',
            name='cotizacion',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='productos',
                to='cotizaciones.cotizacion',
                null=False  # Aseguramos que no acepte NULL
            ),
        ),
    ]